spring.config.import=optional:file:.env[.properties]

server.port=${SERVICE_PORT}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.auto-commit=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.datasource.hikari.register-mbeans=true
# SSL
server.ssl.key-store=${KEY_STORE}
server.ssl.key-store-password=${KEY_STORE_PASSWORD}
# PKCS12 or JKS
server.ssl.keyStoreType=PKCS12